//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSR_Medical.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeEnterArchive
    {
        public int Id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string Login { get; set; }
        public bool isSuccessfull { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
